console.log(6, typeof 6);
console.log('Pepe', typeof 'Pepe');
console.log(true, typeof true);
console.log(undefined, typeof undefined);
console.log(null, typeof null);
console.log(5n, typeof 5n);
console.log(Symbol(), typeof Symbol());
console.log({}, typeof {});
console.log([], typeof []);
console.log(() => {}, typeof (() => {}));
